# Generated by Django 4.0.3 on 2022-06-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='club/')),
                ('game', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('scored', models.IntegerField(default=0)),
                ('missed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_start', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('second_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two', to='mainapp.club')),
                ('third_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three', to='mainapp.club')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one', to='mainapp.club')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_start', models.DateField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_club_result', models.PositiveIntegerField(blank=True, null=True)),
                ('second_club_result', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('first_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to='mainapp.club')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.round')),
                ('second_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to='mainapp.club')),
            ],
        ),
    ]
